services:
  back:
    container_name: sigapp-backend
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    restart: always
    volumes:
      - .:/var/www:delegated
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - CENTRAL_DOMAINS=localhost,127.0.0.1,sigapp-backend
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=sigapp
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SANCTUM_STATEFUL_DOMAINS=localhost:8080,localhost:3000,sigapp.test,*.sigapp.test
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - redis
    networks:
      - database_sigapp

  redis:
    container_name: sigapp-redis
    image: redis:7-alpine
    restart: always
    networks:
      - database_sigapp

networks:
  database_sigapp:
    external: true
