services:
  back:
    container_name: sigapp-backend
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - .:/var/www:delegated
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=sigapp
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - database_sigapp

  redis:
    container_name: sigapp-redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - database_sigapp

networks:
  database_sigapp:
    external: true
