<?php

return [
    'plans' => [
        'broker' => [
            'features' => [
                'home' => true,
                'dashboard' => [
                    'enabled' => false,
                    'overview' => false,
                    'units_closed' => false,
                    'vgv' => false,
                    'funnel' => false,
                ],
                'prospection' => true,
                'viabilities' => [
                    'enabled' => false,
                    'summary' => false,
                    'dre' => false,
                    'cash_flow' => false,
                    'charts' => false,
                    'premises' => false,
                    'kpis' => false,
                ],
                'committee' => false,
                'negotiation' => false,
                'legalizations' => false,
                'projects_room' => false,
                'product_settings' => true,
                'regionals' => true,
                'territorial_base' => true,
                'exports' => [
                    'excel' => true,
                    'pdf' => false,
                ],
            ],
            'limits' => [
                'users' => 1,
                'terrenos' => 50,
                'products' => 1,
                'storage_gb' => 0,
            ],
        ],
        'basico' => [
            'features' => [
                'home' => true,
                'dashboard' => [
                    'enabled' => true,
                    'overview' => true,
                    'units_closed' => false,
                    'vgv' => false,
                    'funnel' => false,
                ],
                'prospection' => true,
                'viabilities' => [
                    'enabled' => true,
                    'summary' => true,
                    'dre' => true,
                    'cash_flow' => false,
                    'charts' => false,
                    'premises' => false,
                    'kpis' => false,
                ],
                'committee' => false,
                'negotiation' => false,
                'legalizations' => false,
                'projects_room' => false,
                'product_settings' => true,
                'regionals' => true,
                'territorial_base' => true,
                'exports' => [
                    'excel' => true,
                    'pdf' => true,
                ],
            ],
            'limits' => [
                'users' => 3,
                'terrenos' => 100,
                'products' => 2,
                'storage_gb' => 1,
            ],
        ],
        'master' => [
            'features' => [
                'home' => true,
                'dashboard' => [
                    'enabled' => true,
                    'overview' => true,
                    'units_closed' => true,
                    'vgv' => true,
                    'funnel' => true,
                ],
                'prospection' => true,
                'viabilities' => [
                    'enabled' => true,
                    'summary' => true,
                    'dre' => true,
                    'cash_flow' => true,
                    'charts' => false,
                    'premises' => false,
                    'kpis' => false,
                ],
                'committee' => false,
                'negotiation' => false,
                'legalizations' => false,
                'projects_room' => false,
                'product_settings' => true,
                'regionals' => true,
                'territorial_base' => true,
                'exports' => [
                    'excel' => true,
                    'pdf' => true,
                ],
            ],
            'limits' => [
                'users' => 10,
                'terrenos' => 200,
                'products' => 3,
                'storage_gb' => 3,
            ],
        ],
        'pro' => [
            'features' => [
                'home' => true,
                'dashboard' => [
                    'enabled' => true,
                    'overview' => true,
                    'units_closed' => true,
                    'vgv' => true,
                    'funnel' => true,
                ],
                'prospection' => true,
                'viabilities' => [
                    'enabled' => true,
                    'summary' => true,
                    'dre' => true,
                    'cash_flow' => true,
                    'charts' => true,
                    'premises' => true,
                    'kpis' => true,
                ],
                'committee' => true,
                'negotiation' => true,
                'legalizations' => true,
                'projects_room' => true,
                'product_settings' => true,
                'regionals' => true,
                'territorial_base' => true,
                'exports' => [
                    'excel' => true,
                    'pdf' => true,
                ],
            ],
            'limits' => [
                'users' => -1,
                'terrenos' => -1,
                'products' => -1,
                'storage_gb' => 5,
            ],
        ],
    ],
];
