[supervisord]
nodaemon=true
user=root

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-tenant-provisioning]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=tenant-provisioning --sleep=1 --tries=3 --timeout=600 --max-time=3600
user=www-data
numprocs=%(ENV_QUEUE_TENANT_PROVISIONING_PROCESSES)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=660
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-ai]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=ai --sleep=1 --tries=3 --timeout=600 --max-time=3600
user=www-data
numprocs=%(ENV_QUEUE_AI_PROCESSES)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=660
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-exports]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=exports --sleep=1 --tries=3 --timeout=600 --max-time=3600
user=www-data
numprocs=%(ENV_QUEUE_EXPORTS_PROCESSES)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=660
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-notifications]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=notifications --sleep=1 --tries=3 --timeout=600 --max-time=3600
user=www-data
numprocs=%(ENV_QUEUE_NOTIFICATIONS_PROCESSES)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=660
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --queue=default --sleep=1 --tries=3 --timeout=600 --max-time=3600
user=www-data
numprocs=%(ENV_QUEUE_DEFAULT_PROCESSES)s
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=660
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=php /var/www/artisan schedule:work
user=www-data
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
